# Generated by Django 4.2.25 on 2025-10-21 15:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiopost',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
    ]
