"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Load local env.py early so environment variables are available for Cloudinary
if os.path.isfile('env.py'):
    import env

if os.environ.get('CLOUDINARY_URL'):
    # Parse CLOUDINARY_URL of the form cloudinary://<api_key>:<api_secret>@<cloud_name>
    _c_url = os.environ.get('CLOUDINARY_URL')
    try:
        _parts = _c_url.split('://', 1)[1]
        creds, cloud = _parts.split('@', 1)
        api_key, api_secret = creds.split(':', 1)
        cloud_name = cloud
        cloudinary.config(cloud_name=cloud_name, api_key=api_key, api_secret=api_secret, secure=True)
    except Exception:
        # Fallback to default behavior; cloudinary will raise a clearer error later
        cloudinary.config(secure=True)
else:
    cloudinary.config(
        cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
        api_key=os.environ.get('CLOUDINARY_API_KEY'),
        api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
        secure=True
    )

# Runtime check: ensure Cloudinary credentials are available in non-test runs.
# By default we enforce credentials to fail fast on misconfiguration. However,
# some management commands (for example `collectstatic`) and CI jobs may not
# need real Cloudinary credentials. To allow those workflows to proceed without
# setting production secrets, we support an opt-in skip via the
# `SKIP_CLOUDINARY_CHECK=1` environment variable. Skipping is intentionally
# conservative and must be enabled explicitly.

# Determine whether to skip the check. Always skip during test runs.
_skip_for_tests = 'test' in sys.argv
_skip_env = os.environ.get('SKIP_CLOUDINARY_CHECK') == '1'
_skip_for_commands = any(cmd in sys.argv for cmd in ('collectstatic', 'check'))

if not (_skip_for_tests or _skip_env or _skip_for_commands):
    if not (
        os.environ.get('CLOUDINARY_URL')
        or (
            os.environ.get('CLOUDINARY_API_KEY')
            and os.environ.get('CLOUDINARY_API_SECRET')
            and os.environ.get('CLOUDINARY_CLOUD_NAME')
        )
    ):
        raise RuntimeError(
            "Cloudinary credentials are missing. Set either CLOUDINARY_URL or the three vars: "
            "CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET. "
            "To bypass this check in CI for allowed commands set SKIP_CLOUDINARY_CHECK=1. "
            "On Heroku run: heroku config:set CLOUDINARY_URL='cloudinary://<key>:<secret>@<name>' -a <appname>"
        )
else:
    # Make skipping visible in logs/console so deploys show the decision.
    import warnings

    warnings.warn(
        "Cloudinary credential check skipped (test run, SKIP_CLOUDINARY_CHECK, or allowed command)."
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'mixes',
    'cloudinary',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
}

CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net/",
    "https://*.herokuapp.com"
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Use a leading slash for STATIC_URL so generated static paths are absolute.
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise's storage backend for serving compressed static files in production.
# Remember to run `python3 manage.py collectstatic` on deploy so files are copied to STATIC_ROOT.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Use Cloudinary for all media file storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add this at the end of your settings.py
if 'test' in sys.argv:
    DATABASES['default']['TEST'] = {
        'MIRROR': None,
        'NAME': 'test_' + DATABASES['default']['NAME'],
        'SERIALIZE': False,
        'DEPENDENCIES': [],
        'CREATE_DB': True,
    }
    # During tests, use local file storage to avoid uploading test files to Cloudinary
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_ROOT = BASE_DIR / 'test_media'