# Generated by Django 4.2.25 on 2025-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopost',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
